#!/bin/bash

# set the ip address
odbedit -c "set \"/Equipment/HV-0/Settings/Devices/sy2527/DD/IP\" 192.168.1.65"

# slots packed from most significant bit down (ie slot 0 in bits 31
# and 30, slot 1 in 29 and 28....)  
#   00 -> empty slot
#   01 -> 12chan card
#   10 -> 24chan card, 
#   11 -> 48chan card
# We have 24 ch in slot0, 12 ch in slot4 and 12 ch in slot5
# 1000000001010000000000000000000b = 1076363264 decimal
odbedit -c "set \"/Equipment/HV-0/Settings/Devices/sy2527/DD/crateMap\" 1076363264" 

# Connection type (0:TCP/IP, 1:, 2:)
odbedit -c "set \"/Equipment/HV-0/Settings/Devices/sy2527/DD/LinkType\" 0"

# set names of first 24 channels
odbedit -c "set \"Equipment/HV-0/Settings/Names[00]\" \"HVCH00\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[01]\" \"HVCH01\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[02]\" \"HVCH02\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[03]\" \"HVCH03\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[04]\" \"HVCH04\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[05]\" \"HVCH05\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[06]\" \"HVCH06\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[07]\" \"HVCH07\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[08]\" \"HVCH08\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[09]\" \"HVCH09\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[10]\" \"HVCH10\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[11]\" \"HVCH11\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[12]\" \"HVCH12\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[13]\" \"HVCH13\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[14]\" \"HVCH14\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[15]\" \"HVCH15\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[16]\" \"HVCH16\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[17]\" \"HVCH17\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[18]\" \"HVCH18\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[19]\" \"HVCH19\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[20]\" \"HVCH20\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[21]\" \"HVCH21\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[22]\" \"HVCH22\""
odbedit -c "set \"Equipment/HV-0/Settings/Names[23]\" \"HVCH23\""

# turn off all channels
odbedit -c "set \"Equipment/HV-0/Settings/ChState[0]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[1]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[2]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[3]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[4]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[5]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[6]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[7]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[8]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[9]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[10]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[11]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[12]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[13]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[14]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[15]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[16]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[17]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[18]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[19]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[20]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[21]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[22]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/ChState[23]\" 0"

# Set voltage limits
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[0]\" 900"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[1]\" 900"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[2]\" 900"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[3]\" 900"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[4]\" 900"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[5]\" 900"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[6]\" 900"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[7]\" 900"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[8]\" 900"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[9]\" 900"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[10]\" 900"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[11]\" 900"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[12]\" 900"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[13]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[14]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[15]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[16]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[17]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[18]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[19]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[20]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[21]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[22]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Voltage Limit[23]\" 0"

odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[0]\" 400"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[1]\" 400"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[2]\" 400"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[3]\" 400"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[4]\" 400"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[5]\" 400"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[6]\" 400"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[7]\" 400"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[8]\" 400"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[9]\" 400"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[10]\" 400"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[11]\" 400"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[12]\" 400"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[13]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[14]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[15]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[16]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[17]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[18]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[19]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[20]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[21]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[22]\" 0"
odbedit -c "set \"Equipment/HV-0/Settings/Current Limit[23]\" 0"

# set demand voltages
odbedit -c "set \"Equipment/HV-0/Variables/Demand[0]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[1]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[2]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[3]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[4]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[5]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[6]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[7]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[8]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[9]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[10]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[11]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[12]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[13]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[14]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[15]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[16]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[17]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[18]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[19]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[20]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[21]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[22]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/Demand[23]\" 0"

# turn off all channels
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[0]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[1]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[2]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[3]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[4]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[5]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[6]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[7]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[8]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[9]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[10]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[11]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[12]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[13]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[14]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[15]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[16]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[17]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[18]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[19]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[20]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[21]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[22]\" 0"
odbedit -c "set \"Equipment/HV-0/Variables/ChStatus[23]\" 0"
